version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      devDependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript*"
          - "vitest*"
      coreDependencies:
        patterns:
          - "electron*"
          - "vue"
          - "pinia"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
