name: Publish to NPM

on:
  release:
    types: [published, created]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Clear auth token for OIDC
        run: echo "NODE_AUTH_TOKEN=" >> $GITHUB_ENV
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
